GeneralGui GeneralGui SerializerVersion1
QMainWindowLayout _layout SerializerVersion1
QRubberBand qt_rubberband SerializerVersion1
QAction actionTask_switcher checked true SerializerVersion1
QAction actionBasic_Task_selection checked false SerializerVersion1
QAction actionExit SerializerVersion1
QAction actionLoad_Profile SerializerVersion1
QAction actionSave_Profile SerializerVersion1
QMenuBar menubar SerializerVersion1
QToolButton qt_menubar_ext_button checked false SerializerVersion1
QMenu menuTools SerializerVersion1
QMenu menuFile SerializerVersion1
QStatusBar statusbar SerializerVersion1
QDockWidget settingsDock SerializerVersion1
QDockWidgetTitleButton qt_dockwidget_floatbutton checked false SerializerVersion1
QDockWidgetTitleButton qt_dockwidget_closebutton checked false SerializerVersion1
QWidget dockWidgetContents SerializerVersion1
QDlgBasicTaskSelector BasicTaskSelector SerializerVersion1
QComboBox settingselector currentText STARTOFTEXTVALUE_  _ENDOFTEXTVALUE SerializerVersion1
QLabel label_7 SerializerVersion1
QPushButton stop checked false SerializerVersion1
QComboBox taskselector currentText STARTOFTEXTVALUE_  _ENDOFTEXTVALUE SerializerVersion1
QPushButton start checked false SerializerVersion1
QLabel label_6 SerializerVersion1
QLabel status_label SerializerVersion1
QPushButton reset checked false SerializerVersion1
QCheckBox stopOnNewTask checked false SerializerVersion1
QCheckBox autoResetTask checked false SerializerVersion1
QDlgTaskSwitcher TaskSwitcher SerializerVersion1
QPushButton startButton checked false SerializerVersion1
QListWidget availableList currentRow 0 itemText0 STARTOFTEXTVALUE_ Detect Training 1 _ENDOFTEXTVALUE itemData0 STARTOFTEXTVALUE_  _ENDOFTEXTVALUE SerializerVersion1
QWidget qt_scrollarea_viewport SerializerVersion1
QWidget qt_scrollarea_hcontainer SerializerVersion1
QWidget qt_scrollarea_vcontainer SerializerVersion1
QListWidget selectedList currentRow 1 itemText0 STARTOFTEXTVALUE_ Detect Training 1 _ENDOFTEXTVALUE itemData0 STARTOFTEXTVALUE_ C:/Users/Jesse/Desktop/NERVE/NerveApp/Release/Leinenkugel/L_Detect_Training_1_2.ncf _ENDOFTEXTVALUE itemText1 STARTOFTEXTVALUE_ Detect Training 1 _ENDOFTEXTVALUE itemData1 STARTOFTEXTVALUE_ C:/Users/Jesse/Desktop/NERVE/NerveApp/Release/Leinenkugel/L_Detect_Training_1_3.ncf _ENDOFTEXTVALUE SerializerVersion1
QWidget qt_scrollarea_viewport SerializerVersion1
QWidget qt_scrollarea_hcontainer SerializerVersion1
QWidget qt_scrollarea_vcontainer SerializerVersion1
QLabel label SerializerVersion1
QLabel label_2 SerializerVersion1
QPushButton skipButton checked false SerializerVersion1
QCheckBox stopBetweenProgramsCheckBox checked false SerializerVersion1
QCheckBox autoRestartCheckBox checked true SerializerVersion1
QFrame frame SerializerVersion1
QLineEdit defaultCfgFileDisplay text STARTOFTEXTVALUE_  _ENDOFTEXTVALUE SerializerVersion1
QPushButton defaultSettingsButton checked false SerializerVersion1
QLineEdit specificCfgFileDisplay text STARTOFTEXTVALUE_ L_Detect_Training_1_3.ncf _ENDOFTEXTVALUE SerializerVersion1
QPushButton specificSettingsButton checked false SerializerVersion1
QLabel label_3 SerializerVersion1
QPushButton removeProgramButton checked false SerializerVersion1
QPushButton pauseButton checked false SerializerVersion1
QCheckBox filePathCheckBox checked false SerializerVersion1
